"""Meta-policy engine — uses run history to order candidates and allocate compute budgets."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

import numpy as np

from aml_toolkit.artifacts.meta_policy_recommendation import MetaPolicyRecommendation
from aml_toolkit.artifacts.run_history import DatasetSignature, RunHistoryRecord
from aml_toolkit.core.config import MetaPolicyConfig

logger = logging.getLogger("aml_toolkit")


class MetaPolicyEngine:
    """Cosine-similarity-based candidate prioritization and compute budget allocation.

    Uses run history to find similar past datasets and recommends:
    1. A reordered candidate list (best-expected-first)
    2. Per-candidate compute budget fractions (sum = 1.0)

    Both steps use cosine similarity on numerical DatasetSignature vectors,
    so similar past datasets get more weight in the recommendation.
    """

    def __init__(self, config: MetaPolicyConfig):
        self.config = config

    def recommend(
        self,
        candidate_ids: list[str],
        dataset_sig: DatasetSignature,
        history: list[RunHistoryRecord],
        config: Any = None,  # ToolkitConfig — for constraint checking
    ) -> MetaPolicyRecommendation:
        """Generate a candidate ordering and compute budget recommendation.

        Args:
            candidate_ids: Ordered list of candidate IDs as generated by the registry.
            dataset_sig: DatasetSignature for the current dataset.
            history: Past RunHistoryRecord objects to consult.
            config: ToolkitConfig for constraint enforcement.

        Returns:
            MetaPolicyRecommendation with recommended_order and compute_budget_fractions.
        """
        if not candidate_ids:
            return MetaPolicyRecommendation()

        try:
            return self._recommend(candidate_ids, dataset_sig, history)
        except Exception as e:
            logger.warning(f"MetaPolicyEngine.recommend failed (using defaults): {e}")
            return self._equal_budget(candidate_ids, reason=f"error: {e}")

    def _recommend(
        self,
        candidate_ids: list[str],
        dataset_sig: DatasetSignature,
        history: list[RunHistoryRecord],
    ) -> MetaPolicyRecommendation:
        if not history:
            return self._equal_budget(candidate_ids, reason="no history available")

        # Extract candidate family from candidate ID (e.g. "rf_001" → "rf")
        def get_family(cid: str) -> str:
            return cid.rsplit("_", 1)[0] if "_" in cid else cid

        families = {cid: get_family(cid) for cid in candidate_ids}

        # Score each candidate by cosine-weighted history
        scores: dict[str, float] = {}
        for cid in candidate_ids:
            family = families[cid]
            scores[cid] = self._score_family(
                family, dataset_sig, history, self.config.recency_decay
            )

        # Sort by score descending
        recommended_order = sorted(candidate_ids, key=lambda c: scores[c], reverse=True)

        # Compute budget fractions (softmax of scores to ensure sum = 1)
        score_arr = np.array([scores[c] for c in recommended_order], dtype=np.float64)
        fractions = self._softmax_budget(score_arr)
        compute_budget_fractions = {
            cid: float(frac) for cid, frac in zip(recommended_order, fractions)
        }

        rationale = {
            cid: (
                f"history score={scores[cid]:.4f}, family={families[cid]}"
                if scores[cid] > 0
                else f"no history data for family={families[cid]}"
            )
            for cid in candidate_ids
        }

        return MetaPolicyRecommendation(
            original_order=list(candidate_ids),
            recommended_order=recommended_order,
            compute_budget_fractions=compute_budget_fractions,
            rationale=rationale,
            history_records_used=len(history),
            notes=[f"Reordered {len(candidate_ids)} candidates using {len(history)} history records."],
        )

    def _score_family(
        self,
        family: str,
        sig: DatasetSignature,
        history: list[RunHistoryRecord],
        recency_decay: float,
    ) -> float:
        """Score a candidate family using cosine-weighted history.

        Score = Σ (cosine_sim * recency_weight * was_best_family)
        where was_best_family = 1 if this family was the winning family in that run.
        """
        query_vec = sig.to_vector()
        query_norm = float(np.linalg.norm(query_vec))
        if query_norm < 1e-8:
            return 0.0

        now = datetime.now(timezone.utc)
        weighted_scores: list[float] = []

        for record in history:
            if record.dataset_signature.modality != sig.modality:
                continue

            rec_vec = np.array(record.dataset_signature_vector, dtype=np.float32)
            rec_norm = float(np.linalg.norm(rec_vec))
            if rec_norm < 1e-8:
                continue

            cosine_sim = float(np.dot(query_vec, rec_vec) / (query_norm * rec_norm))

            ts = record.timestamp
            if ts.tzinfo is None:
                ts = ts.replace(tzinfo=timezone.utc)
            days_ago = max(0.0, (now - ts).total_seconds() / 86400.0)
            recency_weight = recency_decay ** days_ago

            # Check if this family won
            best_family = record.best_candidate_family or (
                record.best_candidate_id.rsplit("_", 1)[0] if "_" in record.best_candidate_id else record.best_candidate_id
            )
            family_won = 1.0 if best_family == family else 0.0

            weighted_scores.append(cosine_sim * recency_weight * family_won)

        return float(np.mean(weighted_scores)) if weighted_scores else 0.0

    def _softmax_budget(self, scores: np.ndarray) -> np.ndarray:
        """Convert scores to budget fractions via softmax.

        If all scores are zero, return equal fractions.
        Uses temperature=1 softmax with a small exploration term.
        """
        if scores.sum() < 1e-8 or len(scores) == 0:
            return np.ones(len(scores)) / max(len(scores), 1)

        # Add exploration bonus: a fraction of 1/N to prevent zero allocation
        exploration = self.config.exploration_weight / max(len(scores), 1)
        # Softmax
        exp_scores = np.exp(scores - scores.max())
        softmax = exp_scores / exp_scores.sum()
        # Blend with uniform
        blended = (1.0 - self.config.exploration_weight) * softmax + exploration
        # Normalize to sum exactly to 1
        return blended / blended.sum()

    def _equal_budget(self, candidate_ids: list[str], reason: str = "") -> MetaPolicyRecommendation:
        """Return equal budget allocation with no reordering."""
        n = len(candidate_ids)
        fractions = {cid: 1.0 / n for cid in candidate_ids}
        return MetaPolicyRecommendation(
            original_order=list(candidate_ids),
            recommended_order=list(candidate_ids),
            compute_budget_fractions=fractions,
            history_records_used=0,
            notes=[f"Equal budget allocation ({reason})."] if reason else ["Equal budget allocation."],
        )
